import Head from "next/head";
import { useState } from "react";
import styles from "@/styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faImage } from "@fortawesome/free-regular-svg-icons";
import DisplayImages from "@/Components/DisplayImages";
import ColorThief from "colorthief";

export default function Home() {
  const [uploadedImage, setUploadedImage] = useState(null);
  const [colorPalette, setColorPalette] = useState(null);

  const uploadImage = (e) => {
    const file = e.target.files[0];
    const reader = new FileReader();
    reader.onload = async (event) => {
      const img = new Image();
      // console.log(img);
      img.onload = () => {
        const colorThief = new ColorThief();
        const colorPalette = colorThief.getPalette(img, 5);
        setUploadedImage(event.target.result);
        setColorPalette(colorPalette);

        //console.log(colorPalette);
      };
      img.src = event.target.result;
    };
    //console.log(reader);
    reader.readAsDataURL(file);
  };
  return (
    <>
      <Head>
        <title>ChromaGen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Chroma Gen</h1>
        <div className="input">
          <label htmlFor="file">
            <FontAwesomeIcon icon={faImage} className="custom-icon" />
            Upload Image
          </label>
        </div>
        <input type="file" id="file" hidden onChange={uploadImage} />
      </header>
      <main className={styles.main}>
        <DisplayImages
          uploadedImage={uploadedImage}
          colorPalette={colorPalette}
        />
      </main>
    </>
  );
}
