import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faImage } from "@fortawesome/free-regular-svg-icons";
//const gallery = <i class="fa-solid fa-image"></i>;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Chroma Gen</h1>
        <div className="input">
          <label htmlFor="file">
            <FontAwesomeIcon icon={faImage} className="custom-icon" />
            Upload Image
          </label>
        </div>
        <input type="file" id="file" hidden />
      </header>
      <main className={styles.main}></main>
    </>
  );
}
